<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BankSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $banks = [
            ['bank_code' => '120001', 'name' => '9mobile 9Payment Service Bank', 'slug' => '9mobile-9payment-service-bank-ng', 'is_active' => true],
            ['bank_code' => '404', 'name' => 'Abbey Mortgage Bank', 'slug' => 'abbey-mortgage-bank-ng', 'is_active' => true],
            ['bank_code' => '51204', 'name' => 'Above Only MFB', 'slug' => 'above-only-mfb', 'is_active' => true],
            ['bank_code' => '51312', 'name' => 'Abulesoro MFB', 'slug' => 'abulesoro-mfb-ng', 'is_active' => true],
            ['bank_code' => '044', 'name' => 'Access Bank', 'slug' => 'access-bank', 'is_active' => true],
            ['bank_code' => '063', 'name' => 'Access Bank (Diamond)', 'slug' => 'access-bank-diamond', 'is_active' => true],
            ['bank_code' => '602', 'name' => 'Accion Microfinance Bank', 'slug' => 'accion-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50315', 'name' => 'Aella MFB', 'slug' => 'aella-mfb-ng', 'is_active' => true],
            ['bank_code' => '90077', 'name' => 'AG Mortgage Bank', 'slug' => 'ag-mortgage-bank-ng', 'is_active' => true],
            ['bank_code' => '50036', 'name' => 'Ahmadu Bello University Microfinance Bank', 'slug' => 'ahmadu-bello-university-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '120004', 'name' => 'Airtel Smartcash PSB', 'slug' => 'airtel-smartcash-psb-ng', 'is_active' => true],
            ['bank_code' => '51336', 'name' => 'AKU Microfinance Bank', 'slug' => 'aku-mfb', 'is_active' => true],
            ['bank_code' => '090561', 'name' => 'Akuchukwu Microfinance Bank Limited', 'slug' => 'akuchukwu-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '035A', 'name' => 'ALAT by WEMA', 'slug' => 'alat-by-wema', 'is_active' => true],
            ['bank_code' => '108', 'name' => 'Alpha Morgan Bank', 'slug' => 'alpha-morgan', 'is_active' => true],
            ['bank_code' => '000304', 'name' => 'Alternative bank', 'slug' => 'the-alternative-bank-ng', 'is_active' => true],
            ['bank_code' => '090629', 'name' => 'Amegy Microfinance Bank', 'slug' => 'amegy-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50926', 'name' => 'Amju Unique MFB', 'slug' => 'amju-unique-mfb', 'is_active' => true],
            ['bank_code' => '50083', 'name' => 'Aramoko MFB', 'slug' => 'aramoko-mfb', 'is_active' => true],
            ['bank_code' => '401', 'name' => 'ASO Savings and Loans', 'slug' => 'asosavings', 'is_active' => true],
            ['bank_code' => '50092', 'name' => 'Assets Microfinance Bank', 'slug' => 'assets-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => 'MFB50094', 'name' => 'Astrapolaris MFB LTD', 'slug' => 'astrapolaris-mfb', 'is_active' => true],
            ['bank_code' => '090478', 'name' => 'AVUENEGBE MICROFINANCE BANK', 'slug' => 'avuenegbe-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51351', 'name' => 'AWACASH MICROFINANCE BANK', 'slug' => 'awacash-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51337', 'name' => 'AZTEC MICROFINANCE BANK LIMITED', 'slug' => 'aztec-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '51229', 'name' => 'Bainescredit MFB', 'slug' => 'bainescredit-mfb', 'is_active' => true],
            ['bank_code' => '50117', 'name' => 'Banc Corp Microfinance Bank', 'slug' => 'banc-corp-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50572', 'name' => 'BANKIT MICROFINANCE BANK LTD', 'slug' => 'bankit-microfinance-bank-ltd-ng', 'is_active' => true],
            ['bank_code' => '51341', 'name' => 'BANKLY MFB', 'slug' => 'ampersand-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => 'MFB50992', 'name' => 'Baobab Microfinance Bank', 'slug' => 'baobab-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51100', 'name' => 'BellBank Microfinance Bank', 'slug' => 'bellbank-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51267', 'name' => 'Benysta Microfinance Bank Limited', 'slug' => 'benysta-microfinance-bank-limited', 'is_active' => true],
            ['bank_code' => '50123', 'name' => 'Beststar Microfinance Bank', 'slug' => 'beststar-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50725', 'name' => 'BOLD MFB', 'slug' => 'bold-mfb-ng', 'is_active' => true],
            ['bank_code' => '650', 'name' => 'Bosak Microfinance Bank', 'slug' => 'bosak-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50931', 'name' => 'Bowen Microfinance Bank', 'slug' => 'bowen-microfinance-bank', 'is_active' => true],
            ['bank_code' => 'FC40163', 'name' => 'Branch International Finance Company Limited', 'slug' => 'branch', 'is_active' => true],
            ['bank_code' => '50645', 'name' => 'BuyPower MFB', 'slug' => 'buypower-mfb-ng', 'is_active' => true],
            ['bank_code' => '565', 'name' => 'Carbon', 'slug' => 'carbon', 'is_active' => true],
            ['bank_code' => '51353', 'name' => 'Cashbridge Microfinance Bank Limited', 'slug' => 'cashbridge-mfb-ng', 'is_active' => true],
            ['bank_code' => '865', 'name' => 'CASHCONNECT MFB', 'slug' => 'cashconnect-mfb-ng', 'is_active' => true],
            ['bank_code' => '50823', 'name' => 'CEMCS Microfinance Bank', 'slug' => 'cemcs-microfinance-bank', 'is_active' => true],
            ['bank_code' => '50171', 'name' => 'Chanelle Microfinance Bank Limited', 'slug' => 'chanelle-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '312', 'name' => 'Chikum Microfinance bank', 'slug' => 'chikum-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '023', 'name' => 'Citibank Nigeria', 'slug' => 'citibank-nigeria', 'is_active' => true],
            ['bank_code' => '070027', 'name' => 'CITYCODE MORTAGE BANK', 'slug' => 'citycode-mortage-bank-ng', 'is_active' => true],
            ['bank_code' => '50910', 'name' => 'Consumer Microfinance Bank', 'slug' => 'consumer-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50204', 'name' => 'Corestep MFB', 'slug' => 'corestep-mfb', 'is_active' => true],
            ['bank_code' => '559', 'name' => 'Coronation Merchant Bank', 'slug' => 'coronation-merchant-bank-ng', 'is_active' => true],
            ['bank_code' => 'FC40128', 'name' => 'County Finance Limited', 'slug' => 'county-finance-limited', 'is_active' => true],
            ['bank_code' => '40119', 'name' => 'Credit Direct Limited', 'slug' => 'credit-direct-limited-ng', 'is_active' => true],
            ['bank_code' => '51297', 'name' => 'Crescent MFB', 'slug' => 'crescent-mfb', 'is_active' => true],
            ['bank_code' => '090560', 'name' => 'Crust Microfinance Bank', 'slug' => 'crust-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50216', 'name' => 'CRUTECH MICROFINANCE BANK LTD', 'slug' => 'crutech-microfinance-bank-ltd-ng', 'is_active' => true],
            ['bank_code' => '51334', 'name' => 'Davenport MICROFINANCE BANK', 'slug' => 'davenport-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51450', 'name' => 'Dillon Microfinance Bank', 'slug' => 'dillon-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50162', 'name' => 'Dot Microfinance Bank', 'slug' => 'dot-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50922', 'name' => 'EBSU Microfinance Bank', 'slug' => 'ebsu-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '050', 'name' => 'Ecobank Nigeria', 'slug' => 'ecobank-nigeria', 'is_active' => true],
            ['bank_code' => '50263', 'name' => 'Ekimogun MFB', 'slug' => 'ekimogun-mfb-ng', 'is_active' => true],
            ['bank_code' => '098', 'name' => 'Ekondo Microfinance Bank', 'slug' => 'ekondo-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '090678', 'name' => 'EXCEL FINANCE BANK', 'slug' => 'excel-finance-bank-ng', 'is_active' => true],
            ['bank_code' => '50126', 'name' => 'Eyowo', 'slug' => 'eyowo', 'is_active' => true],
            ['bank_code' => '51318', 'name' => 'Fairmoney Microfinance Bank', 'slug' => 'fairmoney-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50298', 'name' => 'Fedeth MFB', 'slug' => 'fedeth-mfb-ng', 'is_active' => true],
            ['bank_code' => '070', 'name' => 'Fidelity Bank', 'slug' => 'fidelity-bank', 'is_active' => true],
            ['bank_code' => '51314', 'name' => 'Firmus MFB', 'slug' => 'firmus-mfb', 'is_active' => true],
            ['bank_code' => '011', 'name' => 'First Bank of Nigeria', 'slug' => 'first-bank-of-nigeria', 'is_active' => true],
            ['bank_code' => '214', 'name' => 'First City Monument Bank', 'slug' => 'first-city-monument-bank', 'is_active' => true],
            ['bank_code' => '090164', 'name' => 'FIRST ROYAL MICROFINANCE BANK', 'slug' => 'first-royal-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51333', 'name' => 'FIRSTMIDAS MFB', 'slug' => 'firstmidas-mfb-ng', 'is_active' => true],
            ['bank_code' => '413', 'name' => 'FirstTrust Mortgage Bank Nigeria', 'slug' => 'firsttrust-mortgage-bank-nigeria-ng', 'is_active' => true],
            ['bank_code' => '501', 'name' => 'FSDH Merchant Bank Limited', 'slug' => 'fsdh-merchant-bank-limited', 'is_active' => true],
            ['bank_code' => '832', 'name' => 'FUTMINNA MICROFINANCE BANK', 'slug' => 'futminna-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => 'MFB51093', 'name' => 'Garun Mallam MFB', 'slug' => 'garun-mallam-mfb-ng', 'is_active' => true],
            ['bank_code' => '812', 'name' => 'Gateway Mortgage Bank LTD', 'slug' => 'gateway-mortgage-bank', 'is_active' => true],
            ['bank_code' => '00103', 'name' => 'Globus Bank', 'slug' => 'globus-bank', 'is_active' => true],
            ['bank_code' => '090574', 'name' => 'Goldman MFB', 'slug' => 'goldman-mfb-ng', 'is_active' => true],
            ['bank_code' => '100022', 'name' => 'GoMoney', 'slug' => 'gomoney', 'is_active' => true],
            ['bank_code' => '090664', 'name' => 'GOOD SHEPHERD MICROFINANCE BANK', 'slug' => 'good-shepherd-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50739', 'name' => 'Goodnews Microfinance Bank', 'slug' => 'goodnews-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '562', 'name' => 'Greenwich Merchant Bank', 'slug' => 'greenwich-merchant-bank-ng', 'is_active' => true],
            ['bank_code' => '51276', 'name' => 'GROOMING MICROFINANCE BANK', 'slug' => 'grooming-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50368', 'name' => 'GTI MFB', 'slug' => 'gti-mfb-ng', 'is_active' => true],
            ['bank_code' => '058', 'name' => 'Guaranty Trust Bank', 'slug' => 'guaranty-trust-bank', 'is_active' => true],
            ['bank_code' => '51251', 'name' => 'Hackman Microfinance Bank', 'slug' => 'hackman-microfinance-bank', 'is_active' => true],
            ['bank_code' => '50383', 'name' => 'Hasal Microfinance Bank', 'slug' => 'hasal-microfinance-bank', 'is_active' => true],
            ['bank_code' => '120002', 'name' => 'HopePSB', 'slug' => 'hopepsb-ng', 'is_active' => true],
            ['bank_code' => '51211', 'name' => 'IBANK Microfinance Bank', 'slug' => 'IBANK-mfb', 'is_active' => true],
            ['bank_code' => '51279', 'name' => 'IBBU MFB', 'slug' => 'ibbu-mfb-ng', 'is_active' => true],
            ['bank_code' => '51244', 'name' => 'Ibile Microfinance Bank', 'slug' => 'ibile-mfb', 'is_active' => true],
            ['bank_code' => '90012', 'name' => 'Ibom Mortgage Bank', 'slug' => 'ibom-mortgage-bank-ng', 'is_active' => true],
            ['bank_code' => '50439', 'name' => 'Ikoyi Osun MFB', 'slug' => 'ikoyi-osun-mfb', 'is_active' => true],
            ['bank_code' => '50442', 'name' => 'Ilaro Poly Microfinance Bank', 'slug' => 'ilaro-poly-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50453', 'name' => 'Imowo MFB', 'slug' => 'imowo-mfb-ng', 'is_active' => true],
            ['bank_code' => '415', 'name' => 'IMPERIAL HOMES MORTAGE BANK', 'slug' => 'imperial-homes-mortage-bank-ng', 'is_active' => true],
            ['bank_code' => '51392', 'name' => 'INDULGE MFB', 'slug' => 'indulge-mfb-ng', 'is_active' => true],
            ['bank_code' => '50457', 'name' => 'Infinity MFB', 'slug' => 'infinity-mfb', 'is_active' => true],
            ['bank_code' => '070016', 'name' => 'Infinity trust  Mortgage Bank', 'slug' => 'infinity-trust-mortgage-bank-ng', 'is_active' => true],
            ['bank_code' => '090701', 'name' => 'ISUA MFB', 'slug' => 'isua-mfb-ng', 'is_active' => true],
            ['bank_code' => '301', 'name' => 'Jaiz Bank', 'slug' => 'jaiz-bank', 'is_active' => true],
            ['bank_code' => '50502', 'name' => 'Kadpoly MFB', 'slug' => 'kadpoly-mfb', 'is_active' => true],
            ['bank_code' => '51308', 'name' => 'KANOPOLY MFB', 'slug' => 'kanopoly-mfb-ng', 'is_active' => true],
            ['bank_code' => '082', 'name' => 'Keystone Bank', 'slug' => 'keystone-bank', 'is_active' => true],
            ['bank_code' => '899', 'name' => 'Kolomoni MFB', 'slug' => 'kolomoni-mfb-ng', 'is_active' => true],
            ['bank_code' => '100025', 'name' => 'KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)', 'slug' => 'kongapay-tech-ltd', 'is_active' => true],
            ['bank_code' => '50200', 'name' => 'Kredi Money MFB LTD', 'slug' => 'kredi-money-mfb', 'is_active' => true],
            ['bank_code' => '50211', 'name' => 'Kuda Bank', 'slug' => 'kuda-bank', 'is_active' => true],
            ['bank_code' => '90052', 'name' => 'Lagos Building Investment Company Plc.', 'slug' => 'lbic-plc', 'is_active' => true],
            ['bank_code' => '090420', 'name' => 'Letshego Microfinance Bank', 'slug' => 'letshego-microfinance-bank', 'is_active' => true],
            ['bank_code' => '50549', 'name' => 'Links MFB', 'slug' => 'links-mfb', 'is_active' => true],
            ['bank_code' => '031', 'name' => 'Living Trust Mortgage Bank', 'slug' => 'living-trust-mortgage-bank', 'is_active' => true],
            ['bank_code' => '50491', 'name' => 'LOMA MFB', 'slug' => 'loma-mfb-ng', 'is_active' => true],
            ['bank_code' => '303', 'name' => 'Lotus Bank', 'slug' => 'lotus-bank', 'is_active' => true],
            ['bank_code' => '090171', 'name' => 'MAINSTREET MICROFINANCE BANK', 'slug' => 'mainstreet-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50563', 'name' => 'Mayfair MFB', 'slug' => 'mayfair-mfb', 'is_active' => true],
            ['bank_code' => '50304', 'name' => 'Mint MFB', 'slug' => 'mint-mfb', 'is_active' => true],
            ['bank_code' => '946', 'name' => 'Money Master PSB', 'slug' => 'money-master-psb-ng', 'is_active' => true],
            ['bank_code' => '50515', 'name' => 'Moniepoint MFB', 'slug' => 'moniepoint-mfb-ng', 'is_active' => true],
            ['bank_code' => '120003', 'name' => 'MTN Momo PSB', 'slug' => 'mtn-momo-psb-ng', 'is_active' => true],
            ['bank_code' => '090190', 'name' => 'MUTUAL BENEFITS MICROFINANCE BANK', 'slug' => 'mutual-benefits-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '090679', 'name' => 'NDCC MICROFINANCE BANK', 'slug' => 'ndcc-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51361', 'name' => 'NET MICROFINANCE BANK', 'slug' => 'net-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51142', 'name' => 'Nigerian Navy Microfinance Bank Limited', 'slug' => 'nigerian-navy-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '50072', 'name' => 'Nombank MFB', 'slug' => 'nombank-mfb-ng', 'is_active' => true],
            ['bank_code' => '561', 'name' => 'NOVA BANK', 'slug' => 'nova-bank-ng', 'is_active' => true],
            ['bank_code' => '51371', 'name' => 'Novus MFB', 'slug' => 'novus-mfb-ng', 'is_active' => true],
            ['bank_code' => '50629', 'name' => 'NPF MICROFINANCE BANK', 'slug' => 'npf-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51261', 'name' => 'NSUK MICROFINANACE BANK', 'slug' => 'nsuk-microfinanace-bank-ng', 'is_active' => true],
            ['bank_code' => '50697', 'name' => 'OLUCHUKWU MICROFINANCE BANK LTD', 'slug' => 'oluchukwu-microfinance-bank-ltd-ng', 'is_active' => true],
            ['bank_code' => '999992', 'name' => 'OPay Digital Services Limited (OPay)', 'slug' => 'paycom', 'is_active' => true],
            ['bank_code' => '107', 'name' => 'Optimus Bank Limited', 'slug' => 'optimus-bank-ltd', 'is_active' => true],
            ['bank_code' => '100002', 'name' => 'Paga', 'slug' => 'paga', 'is_active' => true],
            ['bank_code' => '999991', 'name' => 'PalmPay', 'slug' => 'palmpay', 'is_active' => true],
            ['bank_code' => '104', 'name' => 'Parallex Bank', 'slug' => 'parallex-bank', 'is_active' => true],
            ['bank_code' => '311', 'name' => 'Parkway - ReadyCash', 'slug' => 'parkway-ready-cash', 'is_active' => true],
            ['bank_code' => '090680', 'name' => 'PATHFINDER MICROFINANCE BANK LIMITED', 'slug' => 'pathfinder-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '100039', 'name' => 'Paystack-Titan', 'slug' => 'titan-paystack', 'is_active' => true],
            ['bank_code' => '50743', 'name' => 'Peace Microfinance Bank', 'slug' => 'peace-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '51226', 'name' => 'PECANTRUST MICROFINANCE BANK LIMITED', 'slug' => 'pecantrust-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '51146', 'name' => 'Personal Trust MFB', 'slug' => 'personal-trust-mfb-ng', 'is_active' => true],
            ['bank_code' => '50746', 'name' => 'Petra Mircofinance Bank Plc', 'slug' => 'petra-microfinance-bank-plc', 'is_active' => true],
            ['bank_code' => 'MFB51452', 'name' => 'Pettysave MFB', 'slug' => 'pettysave-mfb-ng', 'is_active' => true],
            ['bank_code' => '050021', 'name' => 'PFI FINANCE COMPANY LIMITED', 'slug' => 'pfi-finance-company-limited-ng', 'is_active' => true],
            ['bank_code' => '268', 'name' => 'Platinum Mortgage Bank', 'slug' => 'platinum-mortgage-bank-ng', 'is_active' => true],
            ['bank_code' => '00716', 'name' => 'Pocket App', 'slug' => 'pocket', 'is_active' => true],
            ['bank_code' => '076', 'name' => 'Polaris Bank', 'slug' => 'polaris-bank', 'is_active' => true],
            ['bank_code' => '50864', 'name' => 'Polyunwana MFB', 'slug' => 'polyunwana-mfb-ng', 'is_active' => true],
            ['bank_code' => '105', 'name' => 'PremiumTrust Bank', 'slug' => 'premiumtrust-bank-ng', 'is_active' => true],
            ['bank_code' => '050023', 'name' => 'PROSPERIS FINANCE LIMITED', 'slug' => 'prosperis-finance-limited-ng', 'is_active' => true],
            ['bank_code' => '101', 'name' => 'Providus Bank', 'slug' => 'providus-bank', 'is_active' => true],
            ['bank_code' => '51293', 'name' => 'QuickFund MFB', 'slug' => 'quickfund-mfb', 'is_active' => true],
            ['bank_code' => '502', 'name' => 'Rand Merchant Bank', 'slug' => 'rand-merchant-bank', 'is_active' => true],
            ['bank_code' => '090496', 'name' => 'RANDALPHA MICROFINANCE BANK', 'slug' => 'randalpha-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '90067', 'name' => 'Refuge Mortgage Bank', 'slug' => 'refuge-mortgage-bank', 'is_active' => true],
            ['bank_code' => '50761', 'name' => 'REHOBOTH MICROFINANCE BANK', 'slug' => 'rehoboth-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50994', 'name' => 'Rephidim Microfinance Bank', 'slug' => 'rephidim', 'is_active' => true],
            ['bank_code' => '51286', 'name' => 'Rigo Microfinance Bank Limited', 'slug' => 'rigo-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '50767', 'name' => 'ROCKSHIELD MICROFINANCE BANK', 'slug' => 'rockshield-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '125', 'name' => 'Rubies MFB', 'slug' => 'rubies-mfb', 'is_active' => true],
            ['bank_code' => '51113', 'name' => 'Safe Haven MFB', 'slug' => 'safe-haven-mfb-ng', 'is_active' => true],
            ['bank_code' => '40165', 'name' => 'SAGE GREY FINANCE LIMITED', 'slug' => 'sage-grey-finance-limited-ng', 'is_active' => true],
            ['bank_code' => '50582', 'name' => 'Shield MFB', 'slug' => 'shield-mfb-ng', 'is_active' => true],
            ['bank_code' => '106', 'name' => 'Signature Bank Ltd', 'slug' => 'signature-bank-ltd-ng', 'is_active' => true],
            ['bank_code' => '51062', 'name' => 'Solid Allianze MFB', 'slug' => 'solid-allianze-mfb', 'is_active' => true],
            ['bank_code' => '50800', 'name' => 'Solid Rock MFB', 'slug' => 'solid-rock-mfb', 'is_active' => true],
            ['bank_code' => '51310', 'name' => 'Sparkle Microfinance Bank', 'slug' => 'sparkle-microfinance-bank', 'is_active' => true],
            ['bank_code' => '51429', 'name' => 'Springfield Microfinance Bank', 'slug' => 'springfield-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '221', 'name' => 'Stanbic IBTC Bank', 'slug' => 'stanbic-ibtc-bank', 'is_active' => true],
            ['bank_code' => '068', 'name' => 'Standard Chartered Bank', 'slug' => 'standard-chartered-bank', 'is_active' => true],
            ['bank_code' => '090162', 'name' => 'STANFORD MICROFINANCE BANK', 'slug' => 'stanford-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50809', 'name' => 'STATESIDE MICROFINANCE BANK', 'slug' => 'stateside-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '070022', 'name' => 'STB Mortgage Bank', 'slug' => 'stb-mortgage-bank-ng', 'is_active' => true],
            ['bank_code' => '51253', 'name' => 'Stellas MFB', 'slug' => 'stellas-mfb', 'is_active' => true],
            ['bank_code' => '232', 'name' => 'Sterling Bank', 'slug' => 'sterling-bank', 'is_active' => true],
            ['bank_code' => '100', 'name' => 'Suntrust Bank', 'slug' => 'suntrust-bank', 'is_active' => true],
            ['bank_code' => '50968', 'name' => 'Supreme MFB', 'slug' => 'supreme-mfb-ng', 'is_active' => true],
            ['bank_code' => '302', 'name' => 'TAJ Bank', 'slug' => 'taj-bank', 'is_active' => true],
            ['bank_code' => '51269', 'name' => 'Tangerine Money', 'slug' => 'tangerine-money', 'is_active' => true],
            ['bank_code' => '51403', 'name' => 'TENN', 'slug' => 'tenn-ng', 'is_active' => true],
            ['bank_code' => '102', 'name' => 'Titan Bank', 'slug' => 'titan-bank', 'is_active' => true],
            ['bank_code' => '090708', 'name' => 'TransPay MFB', 'slug' => 'transpay-mfb-ng', 'is_active' => true],
            ['bank_code' => '50840', 'name' => 'U&C Microfinance Bank Ltd (U AND C MFB)', 'slug' => 'uc-microfinance-bank-ltd-u-and-c-mfb-ng', 'is_active' => true],
            ['bank_code' => '090706', 'name' => 'UCEE MFB', 'slug' => 'ucee-mfb-ng', 'is_active' => true],
            ['bank_code' => '51322', 'name' => 'Uhuru MFB', 'slug' => 'uhuru-mfb-ng', 'is_active' => true],
            ['bank_code' => '51080', 'name' => 'Ultraviolet Microfinance Bank', 'slug' => 'ultraviolet-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50870', 'name' => 'Unaab Microfinance Bank Limited', 'slug' => 'unaab-microfinance-bank-limited-ng', 'is_active' => true],
            ['bank_code' => '51447', 'name' => 'UNIABUJA MFB', 'slug' => 'uniabuja-mfb', 'is_active' => true],
            ['bank_code' => '50871', 'name' => 'Unical MFB', 'slug' => 'unical-mfb', 'is_active' => true],
            ['bank_code' => '51316', 'name' => 'Unilag Microfinance Bank', 'slug' => 'unilag-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '50875', 'name' => 'UNIMAID MICROFINANCE BANK', 'slug' => 'unimaid-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '032', 'name' => 'Union Bank of Nigeria', 'slug' => 'union-bank-of-nigeria', 'is_active' => true],
            ['bank_code' => '033', 'name' => 'United Bank For Africa', 'slug' => 'united-bank-for-africa', 'is_active' => true],
            ['bank_code' => '215', 'name' => 'Unity Bank', 'slug' => 'unity-bank', 'is_active' => true],
            ['bank_code' => '50894', 'name' => 'Uzondu Microfinance Bank Awka Anambra State', 'slug' => 'uzondu-microfinance-bank-awka-anambra-state-ng', 'is_active' => true],
            ['bank_code' => '050020', 'name' => 'Vale Finance Limited', 'slug' => 'vale-finance', 'is_active' => true],
            ['bank_code' => '566', 'name' => 'VFD Microfinance Bank Limited', 'slug' => 'vfd', 'is_active' => true],
            ['bank_code' => '51355', 'name' => 'Waya Microfinance Bank', 'slug' => 'waya-microfinance-bank-ng', 'is_active' => true],
            ['bank_code' => '035', 'name' => 'Wema Bank', 'slug' => 'wema-bank', 'is_active' => true],
            ['bank_code' => '51386', 'name' => 'Weston Charis MFB', 'slug' => 'weston-charis-mfb-ng', 'is_active' => true],
            ['bank_code' => '100040', 'name' => 'Xpress Wallet', 'slug' => 'xpress-wallet-ng', 'is_active' => true],
            ['bank_code' => '594', 'name' => 'Yes MFB', 'slug' => 'yes-mfb-ng', 'is_active' => true],
            ['bank_code' => '057', 'name' => 'Zenith Bank', 'slug' => 'zenith-bank', 'is_active' => true],
        ];

        foreach (array_chunk($banks, 100) as $chunk) {
            $rows = array_map(function ($bank) use ($now) {
                $bank['created_at'] = $now;
                $bank['updated_at'] = $now;
                return $bank;
            }, $chunk);

            DB::table('banks')->upsert(
                $rows,
                ['bank_code'],
                ['name', 'slug', 'is_active', 'updated_at']
            );
        }
    }
}
